# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddp', '0011_subscription_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(max_length=64),
        ),
    ]
